---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: En el lenguaje de programación _Cobra_.
  checked: false
- value: En los humoristas británicos _Monty Python_.
  checked: true
- value: En la picadura de serpiente que sufrió el creador.
  checked: false
name: El sentido de Python
